CREATE TABLE [dbo].[INVOICE]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Prop_ID] int,
	[Date_issued] date,
	[Date_paid] date,
	[Description] nvarchar(max),
	[Cost] FLOAT,
	[Type] nvarchar(12),
	CONSTRAINT INVOICE_PROPERTY_FK
	FOREIGN KEY(Prop_ID) REFERENCES PROPERTY(ID) ON UPDATE CASCADE,
	CONSTRAINT INVOICE_INVTYPE_FK
	FOREIGN KEY(Type) REFERENCES INVOICE_TYPE(Type) ON DELETE SET NULL ON UPDATE CASCADE
)
