CREATE TABLE [dbo].[LANDLORD]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [City] NVARCHAR(50) NOT NULL, 
    [State] NVARCHAR(50) NOT NULL, 
    [Zip] INT NOT NULL, 
    [Phone] NCHAR(10) NOT NULL, 
    [Email] NVARCHAR(50) NOT NULL
)
