CREATE TABLE [dbo].[LEASE]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Prop_ID] INT NOT NULL,
	[Start_date] date,
	[Duration_months] int,
	[Monthly_rent] FLOAT
	CONSTRAINT LEASE_PROPERTY_FK
	FOREIGN KEY(Prop_ID) REFERENCES PROPERTY(ID) ON DELETE CASCADE ON UPDATE CASCADE
)
