CREATE TABLE [dbo].[PROPERTY]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Street] nvarchar(50) NOT NULL,
	[City] nvarchar(50) NOT NULL,
	[State] nvarchar(50) NOT NULL,
	[Zip] int NOT NULL,
	[Value] FLOAT,
	[Lord_ID] int NOT NULL DEFAULT 1,
	[Description] nvarchar(max),
	[Type] nvarchar(12),
	CONSTRAINT PROPERTY_LANDLORD_FK
	FOREIGN KEY(Lord_ID) REFERENCES LANDLORD(ID) ON DELETE SET DEFAULT ON UPDATE CASCADE,
	CONSTRAINT PROPERTY_PROPTYPE_FK
	FOREIGN KEY(Type) REFERENCES PROPERTY_TYPE(Type) ON DELETE SET NULL ON UPDATE CASCADE

)
